"use client";
import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

// ── Markdown simple renderer ──────────────────────────────
function md(t) {
    return t
        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
        .replace(/\*(.*?)\*/g, "<em>$1</em>")
        .replace(/\n/g, "<br/>");
}

// ── PDF Generator ─────────────────────────────────────────
function generatePDF(roadmapData, profileData) {
    const content = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>MENTARA Roadmap — ${roadmapData.business}</title>
<style>
  body { font-family: Arial, sans-serif; background: #fff; color: #111; padding: 40px; max-width: 800px; margin: 0 auto; }
  h1 { color: #6750a4; font-size: 24px; margin-bottom: 4px; }
  h2 { color: #444; font-size: 13px; font-weight: normal; margin-bottom: 32px; }
  .phase { border-left: 4px solid #6750a4; padding: 16px 20px; margin-bottom: 20px; background: #f9f7ff; border-radius: 0 8px 8px 0; }
  .phase-label { font-size: 11px; color: #6750a4; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
  .phase-title { font-size: 16px; font-weight: bold; color: #111; margin-bottom: 12px; }
  .task { font-size: 13px; color: #444; padding: 4px 0; padding-left: 16px; position: relative; }
  .task::before { content: "→"; position: absolute; left: 0; color: #6750a4; }
  .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
  .meta { background: #f5f3ff; padding: 16px; border-radius: 8px; margin-bottom: 28px; display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
  .meta-item label { font-size: 10px; color: #888; text-transform: uppercase; display: block; }
  .meta-item span { font-size: 13px; font-weight: bold; color: #111; }
</style>
</head>
<body>
<h1>🗺️ MENTARA Startup Roadmap</h1>
<h2>AI-Generated Growth Plan — Powered by Cognee Memory</h2>
<div class="meta">
  <div class="meta-item"><label>Venture</label><span>${roadmapData.business}</span></div>
  <div class="meta-item"><label>Stage</label><span>${roadmapData.stage?.toUpperCase()}</span></div>
  <div class="meta-item"><label>Location</label><span>${profileData?.location || "—"}</span></div>
  <div class="meta-item"><label>Generated</label><span>${new Date().toLocaleDateString("en-IN")}</span></div>
</div>
${(roadmapData.phases || []).map((p, i) => `
<div class="phase">
  <div class="phase-label">${p.phase}</div>
  <div class="phase-title">${p.title}</div>
  ${(p.tasks || []).map(t => `<div class="task">${t}</div>`).join("")}
</div>`).join("")}
<div class="footer">
  Generated by MENTARA — AI Startup Mentor That Never Forgets<br/>
  Powered by Cognee Graph-Vector Memory · WeMakeDevs Hackathon 2026
</div>
</body>
</html>`;

    const blob = new Blob([content], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
        setTimeout(() => { win.print(); }, 800);
    }
}

// ── Demo responses (no API key) ───────────────────────────
function getDemoResp(msg, profile) {
    const m = msg.toLowerCase();
    const biz = profile?.business || "tumhara business";
    const loc = profile?.location || "tumhare area";
    const stage = profile?.stage || "early";

    if (/sales|revenue|bikri|low|kam/i.test(m))
        return `**${biz}** ki sales badhane ke liye:\n\n1. **Referral program** shuru karo — existing customers ko discount do ek referral pe\n2. **${loc} ke WhatsApp groups** mein daily "aaj ka special" post karo\n3. **Pricing review** karo — delivery ke baad bhi margin positive hai?\n\n**Aaj ka action:** Apne top 3 customers ko personally call karo.`;

    if (/market|competitor|competition/i.test(m))
        return `**${loc}** market analysis:\n\n- Competitors mostly unorganized hain\n- Tumhara edge: personal touch + quality consistency\n- **Google My Business** setup karo — free aur powerful!\n\n**Aaj ka action:** Google My Business pe ${biz} register karo.`;

    if (/goal|target|week|hafte|plan/i.test(m))
        return `Is hafte ke liye clear goal:\n\n**Goal:** 5 naye customers referral se\n**Kaise:** Top 3 existing customers ko message karo\n**Deadline:** Friday shaam tak\n\nGoal save ho gaya — agla session mein follow-up karunga! 🎯`;

    if (/remember|yaad|memory|know/i.test(m))
        return `Haan, main yaad rakhta hoon! 🧠\n\n• **Business:** ${biz}\n• **Location:** ${loc}\n• **Stage:** ${stage}\n\nCognee memory mein permanently store hai. Koi bhi sawaal poocho!`;

    if (/customer|client|user/i.test(m))
        return `**${biz}** ke liye customer acquisition:\n\n1. **Existing customers** se referral lo\n2. **${loc} communities** — WhatsApp/Facebook groups\n3. **Free trial** — pehle 2-3 demo customers\n\n**Aaj ka action:** 2 customers ko referral offer karo.`;

    if (/roadmap|plan|next step/i.test(m))
        return `Sidebar mein **Growth Horizon** click karo — ${stage} stage ke liye personalized roadmap milega! PDF bhi download kar sakte ho. 🗺️`;

    return `**${biz}** ka context yaad hai mujhe.\n\nThoda aur detail batao — kya specific challenge aa rahi hai abhi? Jitna specific, utni better advice.`;
}

function getDemoRoadmap(stage, profile) {
    const biz = profile?.business || "Your Business";
    const loc = profile?.location || "your area";
    const maps = {
        idea: {
            business: biz, stage: "idea", phases: [
                { phase: "Week 1-2", title: "Validate Idea", color: "v1", tasks: [`${loc} mein 10 potential customers se baat karo`, "Problem real hai ya nahi confirm karo", "Competitor research karo", "Basic unit economics calculate karo"] },
                { phase: "Week 3-4", title: "Build Prototype", color: "v2", tasks: ["Simplest possible version banao", "5 beta users dhundho", "Daily feedback lo", "Pivot karne ka courage rakho"] },
                { phase: "Month 2", title: "First Revenue", color: "v3", tasks: ["First paying customer lo", "Pricing finalize karo", "WhatsApp channel banao", "Weekly revenue track karo"] },
                { phase: "Month 3", title: "Product-Market Fit", color: "v4", tasks: ["10 loyal customers achieve karo", "Retention rate measure karo", "Referral program start karo", "Operations document karo"] }
            ]
        },
        early: {
            business: biz, stage: "early", phases: [
                { phase: "Week 1-2", title: "Validate Problem", color: "v1", tasks: [`${loc} mein 10 customers se baat karo`, `${biz} ki USP confirm karo`, "Competitor pricing check karo", "Unit economics calculate karo"] },
                { phase: "Week 3-4", title: "Build MVP", color: "v2", tasks: ["Simplest version launch karo", "5 pilot customers dhundho", "Daily feedback lo", "2-3 pricing variants test karo"] },
                { phase: "Month 2", title: "First 10 Customers", color: "v3", tasks: ["Referral program launch karo", "WhatsApp group banao", "Weekly sales track karo", "Iterate based on feedback"] },
                { phase: "Month 3", title: "Stabilize", color: "v4", tasks: ["Operations document karo", "First hire soch", "Monthly revenue target set karo", "Customer retention improve karo"] }
            ]
        },
        growing: {
            business: biz, stage: "growing", phases: [
                { phase: "Month 1", title: "Double Down", color: "v1", tasks: ["Best performing channel identify karo", "Top 20% customers pe focus karo", "Processes automate karo", "Team kaam clearly assign karo"] },
                { phase: "Month 2", title: "Expand Base", color: "v2", tasks: ["New acquisition channel test karo", `${loc} se bahar expand karo`, "Partnership explore karo", "Customer LTV improve karo"] },
                { phase: "Month 3", title: "Revenue Optimize", color: "v3", tasks: ["Pricing strategy review karo", "Upsell introduce karo", "Monthly recurring model try karo", "Cashflow manage karo"] },
                { phase: "Month 4+", title: "Scale Prep", color: "v4", tasks: ["Key roles hire karo", "SOP document banao", "Technology invest karo", "Funding options explore karo"] }
            ]
        },
        scaling: {
            business: biz, stage: "scaling", phases: [
                { phase: "Q1", title: "Systems & Team", color: "v1", tasks: ["Middle management hire karo", "Processes automate/delegate karo", "OKRs set karo", "Performance dashboard banao"] },
                { phase: "Q2", title: "Market Expansion", color: "v2", tasks: ["New city enter karo", "Strategic partnerships sign karo", "B2B channel explore karo", "Brand marketing invest karo"] },
                { phase: "Q3", title: "Product Expansion", color: "v3", tasks: ["Adjacent product launch karo", "Premium tier introduce karo", "Feedback se roadmap banao", "Technology moat build karo"] },
                { phase: "Q4", title: "Investor Ready", color: "v4", tasks: ["Financial model clean karo", "Due diligence prepare karo", "Advisory board form karo", "Exit options evaluate karo"] }
            ]
        }
    };
    return maps[stage] || maps.early;
}

function getDemoInsights(profile) {
    const biz = profile?.business || "Your Business";
    const loc = profile?.location || "your area";
    return {
        scores: [
            { label: "Market Fit", val: 62, cls: "v" },
            { label: "Execution", val: 55, cls: "c" },
            { label: "Growth Ready", val: 45, cls: "g" },
            { label: "Resilience", val: 70, cls: "a" }
        ],
        cards: [
            { icon: "💪", type: "str", label: "Strength", text: `${biz} ka local market knowledge aur personal relationships strong foundation hai. ${loc} mein yeh sabse bada edge hai.` },
            { icon: "⚠️", type: "warn", label: "Warning", text: "Main challenge abhi unresolved hai based on conversation history. Scaling se pehle yeh solve karo." },
            { icon: "🎯", type: "opp", label: "Opportunity", text: `${loc} mein competitors ki digital presence near-zero hai — Google My Business + WhatsApp se first mover bano.` },
            { icon: "✅", type: "action", label: "Next Action", text: `Is hafte: 5 existing customers ko call karo aur ek referral maango. ${biz} ke liye yeh highest ROI activity hai.` }
        ]
    };
}

function getDemoResearch(city, age, goal, profile) {
    const biz = profile?.business || "Your Business";
    return {
        meta: { business: biz, city: city || "Local Area", type: profile?.businessType || "Business", generated: new Date().toLocaleDateString("en-IN") },
        sections: [
            { num: "01", title: "Market Overview", content: `<strong>${city || "Local area"}</strong> mein market mostly unorganized hai — tier-2/3 city pattern. Significant first-mover opportunity available.`, tags: null },
            { num: "02", title: "Target Customer Profile", content: `Primary: <strong>${age}</strong>. Decision factors: Trust, Price, Convenience. Discovery: WhatsApp, Referral, Google Maps.`, tags: ["Price-sensitive", "Trust-driven", "Mobile-first", "Local preference", "Referral buyer"] },
            { num: "03", title: "Competitor Analysis", content: "3-8 direct competitors, mostly unorganized. Digital presence near-zero — <strong>huge first-mover opportunity</strong>.", tags: null, table: [["Local Competitors", "3-8 direct", "Unorganized"], ["Digital Presence", "Near zero", "First-mover advantage"], ["Quality", "Inconsistent", "Differentiation possible"]] },
            { num: "04", title: "Growth Opportunities", content: `<strong>1. WhatsApp Marketing</strong> — 80%+ penetration, zero cost<br/><strong>2. Google My Business</strong> — free local SEO<br/><strong>3. B2B Contracts</strong> — offices as bulk buyers`, tags: null },
            { num: "05", title: "90-Day Strategy", content: `<strong>Month 1:</strong> 10 loyal customers + referral program<br/><strong>Month 2:</strong> Google My Business + Instagram setup<br/><strong>Month 3:</strong> B2B client pitch karo`, tags: null }
        ]
    };
}

// ═══════════════════════════════════════════════
// MAIN DASHBOARD
// ═══════════════════════════════════════════════
export default function Dashboard() {
    const router = useRouter();
    const msgsRef = useRef(null);
    const inputRef = useRef(null);

    const [user, setUser] = useState(null);
    const [profile, setProfile] = useState(null);
    const [sessionId, setSessionId] = useState(null);
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState("");
    const [typing, setTyping] = useState(false);

    const [activePanel, setActivePanel] = useState(null);
    const [activeScreen, setActiveScreen] = useState("chat");
    const [sidebarOpen, setSidebarOpen] = useState(true);

    const [stats, setStats] = useState({ sessions: 1, goals: 0, nodes: 0, days: 1 });
    const [memLogs, setMemLogs] = useState(["[System] Memory engine initialized", "[System] Cognee graph layer ready"]);
    const [goalBar, setGoalBar] = useState(null);

    // Panel states
    const [roadmapData, setRoadmapData] = useState(null);
    const [roadmapStage, setRoadmapStage] = useState("early");
    const [insightsData, setInsightsData] = useState(null);
    const [researchData, setResearchData] = useState(null);
    const [researchCity, setResearchCity] = useState("");
    const [researchAge, setResearchAge] = useState("All ages");
    const [researchGoal, setResearchGoal] = useState("Find new customers");
    const [panelLoading, setPanelLoading] = useState(false);

    // Profile edit
    const [editName, setEditName] = useState("");
    const [editBiz, setEditBiz] = useState("");
    const [editLoc, setEditLoc] = useState("");

    // Settings
    const [apiKey, setApiKey] = useState("");
    const [apiSaved, setApiSaved] = useState(false);
    const [themeMode, setThemeMode] = useState("dark");

    // ── Init ─────────────────────────────────────
    useEffect(() => {
        const u = localStorage.getItem("mentara_user");
        const p = localStorage.getItem("mentara_profile");
        const s = localStorage.getItem("mentara_session");
        const onboarded = localStorage.getItem("mentara_onboarded");

        if (!u) { router.replace("/auth"); return; }
        if (!onboarded) { router.replace("/onboard"); return; }

        const uP = JSON.parse(u);
        const pP = JSON.parse(p || "{}");
        const sessId = s || ("s_" + Math.random().toString(36).slice(2, 8));

        setUser(uP);
        setProfile(pP);
        setSessionId(sessId);
        setRoadmapStage(pP.stage || "early");
        setResearchCity(pP.location || "");
        setEditName(uP.name || "");
        setEditBiz(pP.businessName || "");
        setEditLoc(pP.location || "");

        if (!s) localStorage.setItem("mentara_session", sessId);

        setMessages([{
            role: "mentor",
            text: `Venture profile loaded — **${pP.businessName}** initialized in Cognee graph.\n\nLocation: ${pP.location} · Stage: ${pP.stage?.toUpperCase()}\n\nMemory active. Sab kuch yaad rahega across sessions. Koi bhi sawaal poocho!`,
            memUsed: true,
            time: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })
        }]);
    }, []);

    // Auto-scroll
    useEffect(() => {
        if (msgsRef.current) msgsRef.current.scrollTop = msgsRef.current.scrollHeight;
    }, [messages, typing]);

    // ── Send Message ──────────────────────────────
    const send = async (text) => {
        const msg = (text || input).trim();
        if (!msg || !user) return;
        setInput("");

        const time = new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" });
        setMessages(p => [...p, { role: "user", text: msg, time }]);
        setTyping(true);
        addLog(`Query: "${msg.slice(0, 35)}..."`);

        try {
            let data;
            try {
                const res = await fetch(`${API}/api/chat`, {
                    method: "POST", headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ user_id: user.userId, session_id: sessionId, message: msg })
                });
                data = await res.json();
            } catch {
                await new Promise(r => setTimeout(r, 900));
                data = {
                    response: getDemoResp(msg, profile),
                    memory_used: true,
                    goal_detected: /goal|target|week|hafte/i.test(msg),
                    goal_text: msg
                };
            }

            setTyping(false);
            setMessages(p => [...p, {
                role: "mentor", text: data.response, memUsed: data.memory_used,
                time: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })
            }]);
            setStats(s => ({ ...s, nodes: s.nodes + 2 }));
            addLog("Response generated from memory graph");

            if (data.goal_detected) {
                setStats(s => ({ ...s, goals: s.goals + 1 }));
                setGoalBar(data.goal_text || msg);
                setTimeout(() => setGoalBar(null), 6000);
            }
        } catch {
            setTyping(false);
            setMessages(p => [...p, { role: "mentor", text: "Connection error — backend check karo!", memUsed: false, time: "" }]);
        }
    };

    const addLog = (text) => {
        const t = new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit", second: "2-digit" });
        setMemLogs(p => [`[${t}] ${text}`, ...p.slice(0, 6)]);
    };

    // ── Roadmap ───────────────────────────────────
    const genRoadmap = async () => {
        setPanelLoading(true);
        addLog(`Generating ${roadmapStage} roadmap...`);
        try {
            const res = await fetch(`${API}/api/roadmap`, {
                method: "POST", headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ user_id: user.userId, stage: roadmapStage })
            });
            setRoadmapData(await res.json());
        } catch {
            await new Promise(r => setTimeout(r, 800));
            setRoadmapData(getDemoRoadmap(roadmapStage, profile));
        }
        setPanelLoading(false);
        addLog("Roadmap generated from memory nodes");
    };

    // ── Insights ──────────────────────────────────
    const genInsights = async () => {
        setPanelLoading(true);
        addLog("Analysing business health...");
        try {
            const res = await fetch(`${API}/api/insights/${user.userId}`);
            setInsightsData(await res.json());
        } catch {
            await new Promise(r => setTimeout(r, 1000));
            setInsightsData(getDemoInsights(profile));
        }
        setPanelLoading(false);
        addLog("Insights extracted from memory graph");
    };

    // ── Research ──────────────────────────────────
    const genResearch = async () => {
        setPanelLoading(true);
        addLog("Generating market research...");
        try {
            const res = await fetch(`${API}/api/market-research`, {
                method: "POST", headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ user_id: user.userId, city: researchCity, age_group: researchAge, goal: researchGoal })
            });
            setResearchData(await res.json());
        } catch {
            await new Promise(r => setTimeout(r, 1200));
            setResearchData(getDemoResearch(researchCity, researchAge, researchGoal, profile));
        }
        setPanelLoading(false);
        addLog(`Research generated for ${researchCity}`);
    };

    // ── Improve Memory ────────────────────────────
    const improveMemory = async () => {
        addLog("Improving memory graph...");
        try {
            await fetch(`${API}/api/improve`, {
                method: "POST", headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ user_id: user.userId, session_id: sessionId })
            });
        } catch { }
        setMessages(p => [...p, {
            role: "mentor", text: "Memory enrichment complete. Session permanently stored in Cognee graph. 🧬",
            memUsed: true, time: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })
        }]);
        addLog("Memory improved — session bridged to permanent graph");
    };

    // ── New Session ───────────────────────────────
    const newSession = () => {
        const ns = "s_" + Math.random().toString(36).slice(2, 8);
        localStorage.setItem("mentara_session", ns);
        setSessionId(ns);
        setStats(s => ({ ...s, sessions: s.sessions + 1 }));
        setMessages([{
            role: "mentor",
            text: `New session initialized. Previous context retained in Cognee graph.\n\n**${profile?.businessName}** — ${stats.nodes} memory nodes active. Kya naya sawaal hai?`,
            memUsed: true, time: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })
        }]);
        addLog("New session initialized");
    };

    // ── Save Profile ──────────────────────────────
    const saveProfile = () => {
        const u = { ...user, name: editName };
        const p = { ...profile, businessName: editBiz, location: editLoc };
        localStorage.setItem("mentara_user", JSON.stringify(u));
        localStorage.setItem("mentara_profile", JSON.stringify(p));
        setUser(u); setProfile(p);
        setActiveScreen("chat");
        addLog("Profile updated");
    };

    const saveApiKey = () => {
        localStorage.setItem("mentara_api_key", apiKey);
        setApiSaved(true);
        setTimeout(() => setApiSaved(false), 2500);
        addLog("API key saved — restart backend to activate");
    };

    const logout = () => {
        localStorage.clear();
        router.push("/auth");
    };

    if (!user || !profile) return (
        <div className="min-h-screen bg-[#0B0F17] flex items-center justify-center">
            <div className="flex gap-1.5">
                {[0, 1, 2].map(i => <div key={i} className="w-2 h-2 rounded-full bg-[#A78BFA] animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />)}
            </div>
        </div>
    );

    const INP = "w-full bg-[#0B0F17] border border-white/[0.06] rounded-lg px-3 py-2.5 text-white text-sm focus:outline-none focus:border-[#A78BFA]/50 placeholder:text-white/20 font-mono";

    return (
        <div className={`h-screen flex flex-col overflow-hidden ${themeMode === "dark" ? "bg-[#0B0F17] text-[#F3F4F6]" : "bg-[#F1F5F9] text-[#0F172A]"} font-sans antialiased`}>

            {/* ── TOP BAR ── */}
            <header className={`h-14 border-b border-white/[0.04] ${themeMode === "dark" ? "bg-[#0F1420]/80" : "bg-slate-200/90"} backdrop-blur-md flex justify-between items-center px-6 shrink-0 z-40`}>
                <div className="flex items-center gap-4">
                    <button onClick={() => setSidebarOpen(!sidebarOpen)} className="p-1.5 hover:bg-white/[0.04] rounded-md border border-white/[0.04] text-white/40 hover:text-white transition-all">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>
                    </button>
                    <span onClick={() => setActiveScreen("chat")} className="font-mono text-xs font-bold tracking-[0.2em] text-[#A78BFA] cursor-pointer">MENTARA // NODE</span>
                </div>

                <div className="hidden md:flex items-center gap-6 text-[11px] font-mono tracking-wider text-white/40">
                    <span>VENTURE: <span className="text-white font-bold">{profile.businessName}</span></span>
                    <span className="opacity-30">|</span>
                    <span>CLUSTER: <span className="text-[#60A5FA] font-bold">{profile.location?.split(",")[0]}_Market</span></span>
                    <span className="opacity-30">|</span>
                    <span>SESSION: <span className="text-emerald-400 font-bold">{sessionId?.slice(-4).toUpperCase()}</span></span>
                </div>

                <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2 bg-white/[0.02] border border-white/[0.04] px-3 py-1.5 rounded-md font-mono text-[11px]">
                        <div className="w-1.5 h-1.5 rounded-full bg-[#A78BFA] animate-pulse" />
                        <span className="text-white/40">NODES:</span>
                        <span className="text-[#A78BFA] font-bold">{stats.nodes}</span>
                    </div>
                    <button onClick={() => setActiveScreen(activeScreen === "settings" ? "chat" : "settings")}
                        className="p-2 hover:bg-white/[0.04] border border-white/[0.04] rounded-md transition-all text-[#A78BFA]">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                    </button>
                </div>
            </header>

            {/* ── BODY ── */}
            <div className="flex-1 flex overflow-hidden">

                {/* ── LEFT SIDEBAR ── */}
                {sidebarOpen && (
                    <aside className={`w-[240px] h-full flex flex-col ${themeMode === "dark" ? "bg-[#0F1420]/60" : "bg-slate-100"} border-r border-white/[0.04] shrink-0 p-4`}>

                        {/* User card */}
                        <div onClick={() => setActiveScreen("profile")} className="p-3 bg-white/[0.02] border border-white/[0.04] hover:border-[#A78BFA]/30 rounded-xl flex items-center gap-3 cursor-pointer transition-all mb-5">
                            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#6750a4] to-[#A78BFA] flex items-center justify-center font-bold text-white text-sm">
                                {user.name?.[0]?.toUpperCase()}
                            </div>
                            <div>
                                <p className="text-xs font-bold text-white">{user.name}</p>
                                <p className="text-[10px] font-mono text-[#A78BFA] uppercase">{profile.stage} stage</p>
                            </div>
                        </div>

                        {/* Stats */}
                        <div className="grid grid-cols-2 gap-1.5 mb-5">
                            {[["SESSIONS", stats.sessions], ["TARGETS", stats.goals], ["NODES", stats.nodes], ["DAYS", stats.days]].map(([l, v]) => (
                                <div key={l} className="bg-white/[0.02] border border-white/[0.04] rounded-lg p-2.5">
                                    <p className="text-[9px] font-mono text-white/30 uppercase">{l}</p>
                                    <p className="text-sm font-mono font-bold text-[#A78BFA] mt-0.5">{String(v).padStart(2, "0")}</p>
                                </div>
                            ))}
                        </div>

                        {/* Nav */}
                        <nav className="flex flex-col gap-1 flex-1">
                            <p className="text-[9px] font-mono text-white/20 uppercase tracking-widest px-2 mb-1">Workspace</p>
                            {[
                                { id: "chat", icon: "💬", label: "AI Stream Deck" },
                                { id: "profile", icon: "👤", label: "Operator Identity" },
                                { id: "settings", icon: "⚙️", label: "System Config" },
                            ].map(item => (
                                <button key={item.id} onClick={() => { setActiveScreen(item.id); setActivePanel(null); }}
                                    className={`flex items-center gap-2.5 px-3 py-2 text-xs font-mono rounded-lg transition-all text-left w-full
                    ${activeScreen === item.id ? "bg-[#A78BFA]/20 text-[#A78BFA] font-bold" : "text-white/40 hover:bg-white/[0.04] hover:text-white"}`}>
                                    <span>{item.icon}</span>{item.label}
                                </button>
                            ))}

                            {activeScreen === "chat" && <>
                                <p className="text-[9px] font-mono text-white/20 uppercase tracking-widest px-2 mb-1 mt-4">Capabilities</p>
                                {[
                                    { id: "roadmap", icon: "🗺️", label: "Growth Horizon" },
                                    { id: "insights", icon: "📊", label: "Health Matrix" },
                                    { id: "research", icon: "🔍", label: "Market Analysis" },
                                ].map(item => (
                                    <button key={item.id} onClick={() => setActivePanel(activePanel === item.id ? null : item.id)}
                                        className={`flex items-center gap-2.5 px-3 py-2 text-xs font-mono rounded-lg border transition-all text-left w-full
                      ${activePanel === item.id ? "bg-[#A78BFA]/10 border-[#A78BFA]/20 text-[#A78BFA]" : "border-transparent text-white/40 hover:bg-white/[0.04] hover:text-white"}`}>
                                        <span>{item.icon}</span>{item.label}
                                    </button>
                                ))}

                                <div className="h-px bg-white/[0.04] my-2" />
                                <button onClick={improveMemory} className="flex items-center gap-2.5 px-3 py-2 text-xs font-mono rounded-lg text-white/40 hover:bg-white/[0.04] hover:text-white transition-all text-left">
                                    <span>✨</span>Improve Memory
                                </button>
                                <button onClick={newSession} className="flex items-center gap-2.5 px-3 py-2 text-xs font-mono rounded-lg text-rose-400/70 hover:bg-rose-500/10 transition-all text-left">
                                    <span>↺</span>New Session
                                </button>
                            </>}
                        </nav>

                        <button onClick={logout} className="flex items-center justify-center gap-2 py-2 text-xs font-mono text-rose-400 hover:bg-rose-500/10 rounded-lg transition-all">
                            <span>⏻</span>Purge State Node
                        </button>
                    </aside>
                )}

                {/* ── MAIN CONTENT ── */}
                <main className="flex-1 flex overflow-hidden">

                    {/* ── CHAT SCREEN ── */}
                    {activeScreen === "chat" && (
                        <div className="flex-1 flex flex-col overflow-hidden">

                            {/* Stats ribbon */}
                            <div className="grid grid-cols-4 border-b border-white/[0.04] divide-x divide-white/[0.04] shrink-0">
                                {[["Sessions", stats.sessions, "text-[#A78BFA]"], ["Target Milestones", stats.goals, "text-white"], ["Index Elements", stats.nodes, "text-emerald-400"], ["Ecosystem Age", stats.days, "text-[#60A5FA]"]].map(([l, v, c]) => (
                                    <div key={l} className="p-3 text-center">
                                        <p className="text-[9px] font-mono text-white/30 uppercase">{l}</p>
                                        <p className={`text-lg font-mono font-bold ${c} mt-0.5`}>{String(v).padStart(2, "0")}</p>
                                    </div>
                                ))}
                            </div>

                            {/* Messages */}
                            <div ref={msgsRef} className="flex-1 overflow-y-auto p-6 space-y-5">
                                {messages.map((msg, i) => (
                                    <div key={i} className={`${msg.role === "user" ? "flex flex-col items-end" : "space-y-2"} animate-in fade-in slide-in-from-bottom-2 duration-200`}>
                                        {msg.role === "mentor" ? (
                                            <>
                                                <div className="flex items-center gap-2">
                                                    <span className="text-[10px] font-mono font-bold text-[#A78BFA] tracking-widest">MENTARA // AI</span>
                                                    {msg.memUsed && <span className="text-[9px] font-mono px-1.5 py-px bg-[#A78BFA]/10 border border-[#A78BFA]/20 text-[#A78BFA] rounded">🧬 Cognee Connected</span>}
                                                    <span className="text-[9px] font-mono text-white/20">{msg.time}</span>
                                                </div>
                                                <div className="max-w-2xl text-sm leading-relaxed bg-[#121824]/90 border border-white/[0.04] rounded-xl p-4 text-[#E5E7EB]"
                                                    dangerouslySetInnerHTML={{ __html: md(msg.text) }} />
                                            </>
                                        ) : (
                                            <div className="max-w-xl w-full bg-white/[0.02] border border-white/[0.05] rounded-xl p-4">
                                                <div className="flex justify-between mb-2">
                                                    <span className="text-[10px] font-mono font-bold text-white/40 uppercase">Founder // Operator</span>
                                                    <span className="text-[9px] font-mono text-white/20">{msg.time}</span>
                                                </div>
                                                <p className="text-sm text-white/90">{msg.text}</p>
                                            </div>
                                        )}
                                        {i < messages.length - 1 && <div className="w-full h-px bg-white/[0.03] mt-2" />}
                                    </div>
                                ))}

                                {typing && (
                                    <div className="space-y-2 animate-in fade-in duration-200">
                                        <span className="text-[10px] font-mono font-bold text-[#A78BFA] tracking-widest">MENTARA // AI</span>
                                        <div className="flex gap-1.5 items-center py-2">
                                            {[0, 1, 2].map(i => <div key={i} className="w-2 h-2 rounded-full bg-white/20 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />)}
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Goal bar */}
                            {goalBar && (
                                <div className="px-6 py-2 bg-yellow-500/10 border-t border-b border-yellow-500/20 flex items-center justify-between shrink-0">
                                    <p className="text-[11px] font-mono text-yellow-300 uppercase tracking-wider">
                                        🎯 TARGET: '{goalBar.slice(0, 55).toUpperCase()}' SAVED TO GRAPH
                                    </p>
                                    <button onClick={() => setGoalBar(null)} className="text-yellow-300 opacity-60 hover:opacity-100">✕</button>
                                </div>
                            )}

                            {/* Input */}
                            <div className="p-5 border-t border-white/[0.04] shrink-0">
                                <div className="flex gap-2 mb-3 overflow-x-auto pb-1" style={{ scrollbarWidth: "none" }}>
                                    {[["Sales Pipeline Help", "My sales are low, kya karu?"], ["Marketing Strategy", "Low budget pe marketing kaise karu?"], ["Set Weekly Goal", "Is hafte ka ek clear goal set karo"], ["Test Memory", "What do you remember about my business?"], ["Get Customers", "First 100 customers kaise laun?"]].map(([l, q]) => (
                                        <button key={l} onClick={() => send(q)} className="flex-shrink-0 px-3 py-1 bg-white/[0.02] border border-white/[0.04] rounded-full text-[11px] font-mono text-white/40 hover:border-[#A78BFA]/40 hover:text-white/80 transition-all">
                                            {l}
                                        </button>
                                    ))}
                                </div>

                                <div className="flex gap-3 items-end bg-[#121824]/80 border border-white/[0.04] focus-within:border-[#A78BFA]/40 rounded-xl p-1.5 transition-all">
                                    <input ref={inputRef} value={input} onChange={e => setInput(e.target.value)}
                                        onKeyDown={e => e.key === "Enter" && !e.shiftKey && send()}
                                        placeholder="Ask strategic advice, compute economics, set goals..."
                                        className="flex-1 bg-transparent border-none outline-none px-3 py-2.5 text-white text-sm placeholder:text-white/20 font-mono" />
                                    <button onClick={() => send()}
                                        className="flex items-center gap-2 px-5 py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-xs uppercase tracking-wider rounded-lg transition-all flex-shrink-0">
                                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" /></svg>
                                        DISPATCH
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* ── PROFILE SCREEN ── */}
                    {activeScreen === "profile" && (
                        <div className="flex-1 overflow-y-auto p-8 max-w-2xl mx-auto w-full space-y-6">
                            <div className="border-b border-white/[0.04] pb-3">
                                <h2 className="text-sm font-mono font-bold text-[#A78BFA] uppercase tracking-wider">👤 Operator Identity Parameters</h2>
                                <p className="text-xs text-white/30 font-mono mt-1">Modify venture context constraints inside the network database.</p>
                            </div>

                            <div className="flex items-center gap-4 p-5 bg-[#121824]/90 border border-white/[0.04] rounded-xl">
                                <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-[#6750a4] to-[#A78BFA] flex items-center justify-center text-white text-2xl font-bold">
                                    {user.name?.[0]?.toUpperCase()}
                                </div>
                                <div>
                                    <p className="font-bold text-white">{user.name}</p>
                                    <p className="text-sm text-white/40">{user.email}</p>
                                    <p className="text-[10px] font-mono text-[#A78BFA] mt-1 uppercase">Founder · {profile.stage} Stage</p>
                                </div>
                            </div>

                            <div className="bg-[#121824]/90 border border-white/[0.04] rounded-xl p-6 space-y-4">
                                {[["Your Name", editName, setEditName, "Operator Real Name"], ["Venture Name", editBiz, setEditBiz, "Business Identifier"], ["Location", editLoc, setEditLoc, "Market Cluster"]].map(([k, v, fn, lbl]) => (
                                    <div key={k}>
                                        <label className="block text-[10px] font-mono text-white/30 uppercase tracking-widest mb-1.5">{lbl}</label>
                                        <input value={v} onChange={e => fn(e.target.value)} className={INP} />
                                    </div>
                                ))}

                                <div className="flex gap-3 pt-2">
                                    <button onClick={saveProfile} className="flex-1 py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-xs uppercase rounded-lg transition-all">
                                        Commit Identity State
                                    </button>
                                    <button onClick={() => setActiveScreen("chat")} className="px-4 py-2.5 bg-white/[0.02] border border-white/[0.04] text-white/40 font-mono text-xs rounded-lg hover:bg-white/[0.05]">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* ── SETTINGS SCREEN ── */}
                    {activeScreen === "settings" && (
                        <div className="flex-1 overflow-y-auto p-8 max-w-2xl mx-auto w-full space-y-5">
                            <div className="border-b border-white/[0.04] pb-3">
                                <h2 className="text-sm font-mono font-bold text-emerald-400 uppercase tracking-wider">⚙️ System Platform Architecture</h2>
                                <p className="text-xs text-white/30 font-mono mt-1">Configure runtime environment and API connections.</p>
                            </div>

                            {/* API Key */}
                            <div className="bg-[#121824]/90 border border-white/[0.04] rounded-xl p-5 space-y-3">
                                <h3 className="text-xs font-mono font-bold text-white uppercase tracking-wider">OpenAI / Cognee API Key</h3>
                                <p className="text-[11px] text-white/30 font-mono">API key milte hi yahan add karo — MENTARA turant real AI mode mein switch ho jayega.</p>
                                <input value={apiKey} onChange={e => setApiKey(e.target.value)} type="password" placeholder="sk-proj-... or cog-..." className={INP} />
                                <button onClick={saveApiKey} className="w-full py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-xs uppercase rounded-lg transition-all">
                                    {apiSaved ? "✅ SAVED!" : "SAVE API KEY"}
                                </button>
                            </div>

                            {/* Theme */}
                            <div className="bg-[#121824]/90 border border-white/[0.04] rounded-xl p-5 space-y-3">
                                <h3 className="text-xs font-mono font-bold text-white uppercase tracking-wider">Layout Visual Mode</h3>
                                <div className="flex gap-2">
                                    {["dark", "light"].map(m => (
                                        <button key={m} onClick={() => setThemeMode(m)} className={`flex-1 py-2 text-xs font-mono rounded-lg border transition-all capitalize ${themeMode === m ? "bg-[#A78BFA]/20 border-[#A78BFA]/40 text-[#A78BFA]" : "border-white/[0.04] text-white/40 hover:border-white/[0.1]"}`}>
                                            {m === "dark" ? "🌙 Dark Core" : "☀️ Light Mode"}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            {/* Backend status */}
                            <div className="bg-[#121824]/90 border border-white/[0.04] rounded-xl p-5 flex items-center justify-between">
                                <div>
                                    <h3 className="text-xs font-mono font-bold text-white uppercase">Backend URL</h3>
                                    <p className="text-[11px] text-emerald-400 font-mono mt-1">{API}</p>
                                </div>
                                <span className="px-2 py-1 rounded text-[10px] font-mono bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">CONNECTED</span>
                            </div>

                            {/* Danger zone */}
                            <div className="bg-[#121824]/90 border border-rose-500/20 rounded-xl p-5 space-y-3">
                                <h3 className="text-xs font-mono font-bold text-rose-400 uppercase">Danger Zone</h3>
                                <button onClick={() => { if (confirm("Reset everything?")) { localStorage.clear(); router.push("/auth"); } }}
                                    className="w-full py-2.5 border border-rose-500/30 text-rose-400 hover:bg-rose-500/10 font-mono text-xs uppercase rounded-lg transition-all">
                                    PURGE ALL DATA
                                </button>
                            </div>
                        </div>
                    )}

                    {/* ── RIGHT PANEL (capabilities) ── */}
                    {activeScreen === "chat" && (
                        <div className="w-72 flex flex-col bg-[#0F1420]/10 border-l border-white/[0.04] shrink-0 overflow-y-auto">

                            {/* Memory log */}
                            <div className="p-4 border-b border-white/[0.04]">
                                <h4 className="text-[10px] font-mono text-[#A78BFA] uppercase tracking-widest mb-3 flex items-center gap-1.5">
                                    <span>⬢</span> COGNEE MEMORY LOG
                                </h4>
                                <div className="space-y-1.5 max-h-32 overflow-hidden">
                                    {memLogs.map((l, i) => <p key={i} className="text-[10px] font-mono text-white/30 truncate">{l}</p>)}
                                </div>
                            </div>

                            {/* Active panel content */}
                            {activePanel && (
                                <div className="flex-1 p-4 overflow-y-auto">
                                    <div className="flex justify-between items-center mb-4">
                                        <h4 className="text-[11px] font-mono font-bold text-[#A78BFA] uppercase">
                                            {activePanel === "roadmap" && "🗺️ Growth Horizon"}
                                            {activePanel === "insights" && "📊 Health Matrix"}
                                            {activePanel === "research" && "🔍 Market Analysis"}
                                        </h4>
                                        <button onClick={() => setActivePanel(null)} className="text-[10px] font-mono text-white/30 hover:text-white">[CLOSE]</button>
                                    </div>

                                    {/* ROADMAP */}
                                    {activePanel === "roadmap" && (
                                        <div className="space-y-3">
                                            <div className="flex gap-1 p-1 bg-white/[0.02] border border-white/[0.04] rounded-lg">
                                                {["idea", "early", "growing", "scaling"].map(s => (
                                                    <button key={s} onClick={() => setRoadmapStage(s)} className={`flex-1 text-[9px] font-mono py-1 rounded capitalize transition-all ${roadmapStage === s ? "bg-[#A78BFA]/20 text-[#A78BFA]" : "text-white/30 hover:text-white"}`}>{s}</button>
                                                ))}
                                            </div>

                                            {roadmapData ? (
                                                <>
                                                    <div className="space-y-2">
                                                        {roadmapData.phases?.map((p, i) => (
                                                            <div key={i} className="p-3 bg-white/[0.02] border border-white/[0.04] rounded-lg">
                                                                <div className="flex gap-2 items-center mb-1.5">
                                                                    <span className="text-[9px] font-mono text-[#A78BFA]">{p.phase}</span>
                                                                    <span className="text-[10px] font-mono font-bold text-white">{p.title}</span>
                                                                </div>
                                                                {p.tasks?.map((t, j) => (
                                                                    <p key={j} className="text-[11px] text-white/40 flex gap-1.5 mb-1"><span className="text-[#A78BFA]">→</span>{t}</p>
                                                                ))}
                                                            </div>
                                                        ))}
                                                    </div>
                                                    <button onClick={() => generatePDF(roadmapData, profile)}
                                                        className="w-full py-2 bg-[#A78BFA]/20 border border-[#A78BFA]/30 text-[#A78BFA] font-mono text-[11px] uppercase rounded-lg hover:bg-[#A78BFA]/30 transition-all">
                                                        📄 Download PDF
                                                    </button>
                                                </>
                                            ) : (
                                                <p className="text-[11px] font-mono text-white/20 text-center py-4">Click generate to create roadmap</p>
                                            )}

                                            <button onClick={genRoadmap} disabled={panelLoading}
                                                className="w-full py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-[11px] uppercase rounded-lg disabled:opacity-50 transition-all">
                                                {panelLoading ? "⏳ Generating..." : "🗺️ Generate Roadmap"}
                                            </button>
                                        </div>
                                    )}

                                    {/* INSIGHTS */}
                                    {activePanel === "insights" && (
                                        <div className="space-y-3">
                                            {insightsData ? (
                                                <>
                                                    <div className="p-3 bg-white/[0.02] border border-white/[0.04] rounded-lg space-y-2">
                                                        <p className="text-[9px] font-mono text-white/30 uppercase">Health Matrix</p>
                                                        {insightsData.scores?.map((s, i) => (
                                                            <div key={i} className="flex items-center gap-2">
                                                                <span className="text-[9px] font-mono text-white/30 w-20 truncate">{s.label}</span>
                                                                <div className="flex-1 h-1 bg-white/[0.05] rounded-full overflow-hidden">
                                                                    <div className="h-full bg-[#A78BFA] rounded-full transition-all duration-700" style={{ width: `${s.val}%` }} />
                                                                </div>
                                                                <span className="text-[10px] font-mono text-[#A78BFA] font-bold">{s.val}</span>
                                                            </div>
                                                        ))}
                                                    </div>
                                                    {insightsData.cards?.map((c, i) => (
                                                        <div key={i} className="p-3 bg-white/[0.02] border border-white/[0.04] rounded-lg">
                                                            <p className="text-[9px] font-mono text-[#A78BFA] font-bold uppercase mb-1">{c.icon} {c.label}</p>
                                                            <p className="text-[11px] text-white/40 leading-relaxed">{c.text}</p>
                                                        </div>
                                                    ))}
                                                </>
                                            ) : (
                                                <p className="text-[11px] font-mono text-white/20 text-center py-4">Click analyse to get insights</p>
                                            )}
                                            <button onClick={genInsights} disabled={panelLoading}
                                                className="w-full py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-[11px] uppercase rounded-lg disabled:opacity-50 transition-all">
                                                {panelLoading ? "⏳ Analysing..." : "📊 Analyse Business"}
                                            </button>
                                        </div>
                                    )}

                                    {/* RESEARCH */}
                                    {activePanel === "research" && (
                                        <div className="space-y-3">
                                            <div>
                                                <label className="block text-[9px] font-mono text-white/30 uppercase mb-1">Target City</label>
                                                <input value={researchCity} onChange={e => setResearchCity(e.target.value)} placeholder="e.g. Jaspur" className={INP} />
                                            </div>
                                            <div>
                                                <label className="block text-[9px] font-mono text-white/30 uppercase mb-1">Age Group</label>
                                                <select value={researchAge} onChange={e => setResearchAge(e.target.value)} className={INP}>
                                                    {["18–25", "25–35", "35–50", "All ages"].map(a => <option key={a}>{a}</option>)}
                                                </select>
                                            </div>
                                            <div>
                                                <label className="block text-[9px] font-mono text-white/30 uppercase mb-1">Research Goal</label>
                                                <select value={researchGoal} onChange={e => setResearchGoal(e.target.value)} className={INP}>
                                                    {["Find new customers", "Understand competitors", "Pricing strategy", "Expansion"].map(g => <option key={g}>{g}</option>)}
                                                </select>
                                            </div>

                                            {researchData && (
                                                <div className="space-y-2">
                                                    {researchData.sections?.map((s, i) => (
                                                        <div key={i} className="p-3 bg-white/[0.02] border border-white/[0.04] rounded-lg">
                                                            <p className="text-[9px] font-mono text-[#A78BFA] font-bold uppercase mb-1">{s.num}. {s.title}</p>
                                                            <div className="text-[11px] text-white/40 leading-relaxed" dangerouslySetInnerHTML={{ __html: s.content }} />
                                                            {s.tags && <div className="flex flex-wrap gap-1 mt-1.5">{s.tags.map(t => <span key={t} className="px-1.5 py-0.5 bg-white/[0.03] border border-white/[0.04] rounded text-[9px] font-mono text-white/30">{t}</span>)}</div>}
                                                        </div>
                                                    ))}
                                                    <div className="flex gap-2">
                                                        <button onClick={() => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([JSON.stringify(researchData, null, 2)], { type: "application/json" })); a.download = `${profile.businessName}_research.json`; a.click(); }}
                                                            className="flex-1 py-1.5 border border-[#A78BFA]/30 text-[#A78BFA] text-[10px] font-mono uppercase rounded-lg hover:bg-[#A78BFA]/10">
                                                            ⬇ JSON
                                                        </button>
                                                        <button onClick={() => { const txt = researchData.sections?.map(s => `${s.num}. ${s.title}\n${s.content.replace(/<[^>]*>/g, "")}`).join("\n\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([txt], { type: "text/plain" })); a.download = `${profile.businessName}_research.txt`; a.click(); }}
                                                            className="flex-1 py-1.5 border border-emerald-500/30 text-emerald-400 text-[10px] font-mono uppercase rounded-lg hover:bg-emerald-500/10">
                                                            ⬇ TXT
                                                        </button>
                                                    </div>
                                                </div>
                                            )}

                                            <button onClick={genResearch} disabled={panelLoading}
                                                className="w-full py-2.5 bg-[#A78BFA] hover:bg-[#9461fa] text-[#0B0F17] font-mono font-bold text-[11px] uppercase rounded-lg disabled:opacity-50 transition-all">
                                                {panelLoading ? "⏳ Generating..." : "🔍 Generate Research"}
                                            </button>
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* Goal tracker */}
                            {!activePanel && (
                                <div className="p-4 border-t border-white/[0.04] mt-auto">
                                    <h4 className="text-[10px] font-mono text-white/30 uppercase tracking-widest mb-3">Active Goal Vector</h4>
                                    <div className="p-3 bg-white/[0.01] border border-white/[0.03] rounded-lg">
                                        {stats.goals > 0 ? (
                                            <>
                                                <div className="flex justify-between text-[11px] mb-2">
                                                    <span className="text-white/50 truncate max-w-[140px]">Active targets</span>
                                                    <span className="text-[#A78BFA] font-mono font-bold">{stats.goals}</span>
                                                </div>
                                                <div className="w-full h-1 bg-white/[0.05] rounded-full overflow-hidden">
                                                    <div className="h-full bg-[#A78BFA]" style={{ width: "20%" }} />
                                                </div>
                                            </>
                                        ) : (
                                            <p className="text-[10px] font-mono text-white/20">No goals tracked yet</p>
                                        )}
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </main>
            </div>
        </div>
    );
}